### ISSUE TITLE
IllegalAccessError with Atomos, modulepath and OpenJ9 sharedclasses

### ISSUE THREAD

**Issue by fipro78** [eclipse-equinox/equinox#158]
I created a small Equinox OSGi application to verify different deployment variants. In this GitHub repository all the sources and a build for creating Docker containers with the different deployment variants are available: https://github.com/fipro78/osgi_deployment_options

I learned at the EclipseCon about OpenJ9 shared classes and therefore wanted to add that option to my setup.

There is one combination that doesn't seem to work. At least the shared class cache is not working.

If I use Atomos with the modulepath and the shared class cache of OpenJ9, I see the following exception:

```
java.lang.IllegalAccessError: Class org/eclipse/osgi/internal/cds/CDSHookImpls(org.eclipse.osgi) can not access class com/ibm/oti/shared/Shared(openj9.sharedclasses) because module org.eclipse.osgi does not read module openj9.sharedclasses
        at org.eclipse.osgi/org.eclipse.osgi.internal.cds.CDSHookImpls.<clinit>(CDSHookImpls.java:47)
        at org.eclipse.osgi/org.eclipse.osgi.internal.cds.CDSHookConfigurator.addHooks(CDSHookConfigurator.java:65)
        at org.eclipse.osgi/org.eclipse.osgi.internal.hookregistry.HookRegistry.loadConfigurators(HookRegistry.java:205)
        at org.eclipse.osgi/org.eclipse.osgi.internal.hookregistry.HookRegistry.initialize(HookRegistry.java:118)
        at org.eclipse.osgi/org.eclipse.osgi.internal.framework.EquinoxContainer.<init>(EquinoxContainer.java:106)
        at org.eclipse.osgi/org.eclipse.osgi.launch.Equinox.<init>(Equinox.java:53)
        at org.eclipse.osgi/org.eclipse.osgi.launch.EquinoxFactory.newFramework(EquinoxFactory.java:35)
        at org.apache.felix.atomos/org.apache.felix.atomos.impl.base.AtomosBase.newFramework(AtomosBase.java:442)
        at org.apache.felix.atomos/org.apache.felix.atomos.Atomos.main(Atomos.java:236)
```

The command I executed in a current OpenJ9 17 container is:

```
java \
  -Xshareclasses:name=app_cache,cacheDir=/app/.scc \
  --add-modules=ALL-MODULE-PATH,java.net.http,openj9.sharedclasses 
  -p bundles \
  -m org.apache.felix.atomos \
  org.osgi.framework.system.packages="" \
  org.osgi.framework.storage=configuration
```

I tried several variants, but the issue is always the same.

**Comment by tjwatson** [comment]
I think we need an update to Equinox for this.  Looks like `openj9.sharedclasses` needs to be statically required (optional) in the `module.info.class` for Equinox `org.eclipse.osgi`.  This is similar to the `jdk.unsupported` static requires specified in the `bnd.bnd` file of the project:

https://github.com/eclipse-equinox/equinox/blob/d1c1ac4ceab2f1ee4634335e5c1da455d877d7da/bundles/org.eclipse.osgi/bnd.bnd#L2

Would you open an issue against equinox and perhaps make your first contribution over there in the form of a PR?

**Comment by tjwatson** [comment]
> Would you open an issue against equinox and perhaps make your first contribution over there in the form of a PR?

Sorry about that, I mistakenly thought this issue was opened in Atomos.  So you already opened the issue here in Equinox!  If possible, please provide a PR like I described!

**Comment by tjwatson** [comment]
Thanks for the PR.  We can merge this for the 2023-03 release.  We are already in release candidates for the current 2022-12 release.

In the meantime can you try using `--add-reads` option:

```
java \
  -Xshareclasses:name=app_cache,cacheDir=/app/.scc \
  --add-modules=ALL-MODULE-PATH,java.net.http,openj9.sharedclasses \
  --add-reads=org.eclipse.osgi=,openj9.sharedclasses \
  -p bundles \
  -m org.apache.felix.atomos \
  org.osgi.framework.system.packages="" \
  org.osgi.framework.storage=configuration
```

**Comment by fipro78** [comment]
Thanks for the pointer, I tested using the `--add-reads` option. It works! Interestingly it increases the shared class cache from 25 MB to 80 MB. I added a note to the README of my repository.

**Comment by tjwatson** [comment]
Need to analyze what is going on with the cache.  In this case we may be double storing the class data.  The equinox support is assuming it defined the class and needs to store it.  But the jvm class loader did, and also stores the class data.
