### ISSUE TITLE
NPE when running a connect framework in another OSGi framework

### ISSUE THREAD

**Issue by laeubi** [eclipse-equinox/equinox#168]
In Tycho we leverage osgi-connect to run some code in an embedded OSGi framework. This works well in plain maven CLI, but m2eclipse runs this also in an embedded mode where m2e itself is running in an OSGi framework.

With this setup we see NPE in equinox when registering a service:

```
java.lang.NullPointerException: Cannot invoke "org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(org.eclipse.osgi.internal.framework.BundleContextImpl, String[], Object, java.util.Dictionary)" because the return value of "org.eclipse.osgi.internal.framework.EquinoxContainer.getServiceRegistry()" is null
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:500)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:519)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:1047)
	at org.eclipse.sisu.osgi.connect.PlexusConnectFramework.registerService(PlexusConnectFramework.java:195)
```

It is not quite clear what happens here exactly but it would be good if equinox would not run into a NPE but instead throw some kind of illegal state exception explain what is going wrong here (e.g. framework not started? or already shut down? something else?

**Comment by laeubi** [comment]
Also a similar one:
`java.lang.NullPointerException: Cannot invoke "org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.addServiceListener(org.eclipse.osgi.internal.framework.BundleContextImpl, org.osgi.framework.ServiceListener, String)" because the return value of "org.eclipse.osgi.internal.framework.EquinoxContainer.getServiceRegistry()" is null`

**Comment by laeubi** [comment]
At the start of the framework Equinox prints the following to System.err
```
org.osgi.framework.BundleException: Could not resolve module: org.apache.felix.scr [102]
  No resolution report for the bundle.
	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:445)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:464)
	at org.eclipse.equinox.internal.simpleconfigurator.ConfigApplier.startBundles(ConfigApplier.java:497)
	at org.eclipse.equinox.internal.simpleconfigurator.ConfigApplier.install(ConfigApplier.java:122)
	at org.eclipse.equinox.internal.simpleconfigurator.SimpleConfiguratorImpl.applyConfiguration(SimpleConfiguratorImpl.java:189)
	at org.eclipse.equinox.internal.simpleconfigurator.SimpleConfiguratorImpl.applyConfiguration(SimpleConfiguratorImpl.java:204)
	at org.eclipse.equinox.internal.simpleconfigurator.Activator.start(Activator.java:64)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:818)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:1)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:810)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:767)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1032)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:371)
	at org.eclipse.osgi.container.Module.doStart(Module.java:605)
	at org.eclipse.osgi.container.Module.start(Module.java:468)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1852)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1845)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1788)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1750)
	at org.eclipse.osgi.container.SystemModule.startWorker(SystemModule.java:269)
	at org.eclipse.osgi.container.Module.doStart(Module.java:605)
	at org.eclipse.osgi.container.Module.start(Module.java:468)
	at org.eclipse.osgi.container.SystemModule.start(SystemModule.java:193)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:445)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:464)
	at org.eclipse.osgi.launch.Equinox.start(Equinox.java:139)
```

I'm not aware that Tycho is actually using SimpleConfigurator?

**Comment by laeubi** [comment]
After this error and when one tries to use the framework the following exception is thrown:
```
19:49:06.062 [Worker-1: Building] WARN org.eclipse.m2e.core.internal.embedder.EclipseLogger - Internal error in EquinoxLifecycleListener org.eclipse.tycho.p2maven.MavenURLStreamHandlerService@725e09f9 Cannot invoke "org.osgi.framework.BundleContext.registerService(java.lang.Class, Object, java.util.Dictionary)" because the return value of "org.osgi.framework.launch.Framework.getBundleContext()" is null
java.lang.NullPointerException: Cannot invoke "org.osgi.framework.BundleContext.registerService(java.lang.Class, Object, java.util.Dictionary)" because the return value of "org.osgi.framework.launch.Framework.getBundleContext()" is null
	at org.eclipse.sisu.osgi.connect.PlexusConnectFramework.registerService(PlexusConnectFramework.java:195)
```
