### ISSUE TITLE
NoClassDefFoundError: org/eclipse/osgi/internal/messages/Msg on shutdown

### ISSUE THREAD

**Issue by laeubi** [eclipse-equinox/equinox#169]
Tycho uses an embedded OSGi connect framework, on shutdown one gets the following warnings:
```
17:42:04.812 [Framework stop - Equinox Container: c1e7a2ac-9f4f-4438-b635-a636b430b156] WARN org.eclipse.m2e.core.internal.embedder.EclipseLogger - Problem disposing: org.eclipse.sisu.osgi.connect.PlexusFrameworkConnectServiceFactory@418c940b org/eclipse/osgi/internal/messages/Msg
java.lang.NoClassDefFoundError: org/eclipse/osgi/internal/messages/Msg
	at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.factoryUngetService(ServiceFactoryUse.java:281)
	at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.ungetService(ServiceFactoryUse.java:164)
	at org.eclipse.osgi.internal.serviceregistry.ServiceConsumer$2.ungetService(ServiceConsumer.java:53)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.ungetService(ServiceRegistrationImpl.java:663)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.ungetService(ServiceRegistry.java:621)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.ungetService(BundleContextImpl.java:703)
	at org.eclipse.sisu.osgi.connect.PlexusConnectFramework$1.removedService(PlexusConnectFramework.java:351)
	at org.eclipse.sisu.osgi.connect.PlexusConnectFramework$1.removedService(PlexusConnectFramework.java:333)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerRemoved(ServiceTracker.java:969)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerRemoved(ServiceTracker.java:1)
	at org.osgi.util.tracker.AbstractTracked.untrack(AbstractTracked.java:341)
	at org.osgi.util.tracker.ServiceTracker.close(ServiceTracker.java:380)
	at org.eclipse.sisu.osgi.connect.PlexusConnectFramework.stop(PlexusConnectFramework.java:360)
	at org.eclipse.sisu.osgi.connect.PlexusFrameworkConnectServiceFactory.lambda$dispose$11(PlexusFrameworkConnectServiceFactory.java:317)
	at java.base/java.util.Collection.removeIf(Collection.java:576)
	at org.eclipse.sisu.osgi.connect.PlexusFrameworkConnectServiceFactory.dispose(PlexusFrameworkConnectServiceFactory.java:311)
```

**Comment by laeubi** [comment]
As the `Msg` class is part of internal equinox code (and part of the same jar) I can not really think how classloading setup can be the issue here? As this happens as a consequence of catching **any** `Throwable` of course maybe there is really another issue?

**Comment by tjwatson** [comment]
What class loader is loading the framework here?  Is it possible that this class loader is "closed" and as a result fails to load any classes?
