### ISSUE TITLE
Potential Deadlock in MRUBundleFileList

### ISSUE THREAD

**Issue by carlwitt** [eclipse-equinox/equinox#220]
I've observed our product's (KNIME) main thread to hang, because class loading via the org.eclipse.osgi.internal.loader.ModuleClassLoader relies on a seemingly non-thread-safe data structure to maintain most recently used statistics on `BundleFile`s, the MRUBundleFileList. 

Although I couldn't identify a cycle in the thread dump, the application didn't make progress for >30 minutes.

Class loading in the main thread cannot proceed because to execute MRUBundleFileList.use it needs to lock MRUBundleFileList.
This lock is held by thread 73.

Thread 73 cannot proceed because to execute MRUBundleFileList.add, it needs to lock the MRUBundleFileList's ReentrantLock pendingLock. The lock on that object is held by thread 27.

Thread 27 is marked as RUNNABLE, but does not make any progress while executing MRUBundleFileList.dispatchEvent.

The relevant portions of the stack trace:
```
"main" #1 prio=6 os_prio=31 cpu=4549.16ms elapsed=180.50s tid=0x00007fc8a5827200 nid=0x103 waiting for monitor entry  [0x00007ff7b36a8000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at org.eclipse.osgi.storage.bundlefile.MRUBundleFileList.use(MRUBundleFileList.java:166) // synchronized (this) 
	- waiting to lock <0x0000000080096090> (a org.eclipse.osgi.storage.bundlefile.MRUBundleFileList) // owned by #76
	at org.eclipse.osgi.storage.bundlefile.CloseableBundleFile.mruListUse(CloseableBundleFile.java:401)
```

```
"ForkJoinPool.commonPool-worker-1" #76 daemon prio=5 os_prio=31 cpu=30.50ms elapsed=174.20s tid=0x00007fc8a6982e00 nid=0x1880b waiting on condition  [0x000070000b314000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@17.0.5/Native Method)
	- parking to wait for  <0x00000000800965d8> (a java.util.concurrent.locks.ReentrantLock$NonfairSync) // owned by #27 via #dispatchEvent
	at java.util.concurrent.locks.LockSupport.park(java.base@17.0.5/Unknown Source)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(java.base@17.0.5/Unknown Source)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(java.base@17.0.5/Unknown Source)
	at java.util.concurrent.locks.ReentrantLock$Sync.lock(java.base@17.0.5/Unknown Source)
	at java.util.concurrent.locks.ReentrantLock.lock(java.base@17.0.5/Unknown Source)
	at org.eclipse.osgi.storage.bundlefile.MRUBundleFileList.isBackPressureNeeded(MRUBundleFileList.java:210) // pendingLock.lock();
	at org.eclipse.osgi.storage.bundlefile.MRUBundleFileList.add(MRUBundleFileList.java:111) // line is in a synchronized (this) block
	- locked <0x0000000080096090> (a org.eclipse.osgi.storage.bundlefile.MRUBundleFileList)
	at org.eclipse.osgi.storage.bundlefile.CloseableBundleFile.mruListAdd(CloseableBundleFile.java:413)
```

```
"Bundle File Closer" #27 daemon prio=5 os_prio=31 cpu=29.95ms elapsed=179.01s tid=0x00007fc8a3af0e00 nid=0x14307 runnable  [0x0000700008ca4000]
   java.lang.Thread.State: RUNNABLE
	at java.util.concurrent.locks.ReentrantLock$Sync.lock(java.base@17.0.5/Unknown Source)
	at java.util.concurrent.locks.ReentrantLock.lock(java.base@17.0.5/Unknown Source)
	at org.eclipse.osgi.storage.bundlefile.MRUBundleFileList.dispatchEvent(MRUBundleFileList.java:198) // pendingLock.lock();
	at org.eclipse.osgi.storage.bundlefile.MRUBundleFileList.dispatchEvent(MRUBundleFileList.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
```

Is this a bug in MRUBundleFileList? Any ideas why `dispatchEvent` might hang?

I've attached the full thread dump.
[threaddump-1677062975859.txt](https://github.com/eclipse-equinox/equinox/files/10813046/threaddump-1677062975859.txt)

**Comment by tjwatson** [comment]
I see no reason `Bundle File Closer" #27 ` is blocked.  

Are you sure it is not proceeding and simply looping over bundle files to close? 

Is this reproducible?

Do you have `osgi.bundlefile.limit` set to something?

**Comment by carlwitt** [comment]
Reproducibility: Difficult. The problem is non-deterministic, I didn't observe it again yet. 
Progress: I waited for >30 minutes, took another thread dump and it showed the exact same state (Main thread transitively waiting on thread 27, which was still in dispatchEvent).
