### ISSUE TITLE
org.eclipse.osgi.tests shows 112 test fails since I20230811-0350

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-equinox/equinox#301]
See for example [org.eclipse.osgi.tests](https://download.eclipse.org/eclipse/downloads/drops4/I20230811-0350/testresults/html/org.eclipse.osgi.tests_ep429I-unit-cen64-gtk3-java17_linux.gtk.x86_64_17.html#org.eclipse.osgi.tests)

All fails look similar, one example
```
Test did not run: testAsyncValue01(org.eclipse.osgi.tests.appadmin.ApplicationAdminTest)

java.lang.Exception: Test did not run: testAsyncValue01(org.eclipse.osgi.tests.appadmin.ApplicationAdminTest)
at org.eclipse.core.tests.session.SessionTestRunner.run(SessionTestRunner.java:306)
at org.eclipse.core.tests.session.TestDescriptor.run(TestDescriptor.java:95)
at org.eclipse.core.tests.session.SessionTestSuite.runSessionTest(SessionTestSuite.java:169)
at org.eclipse.core.tests.session.SessionTestSuite.runTest(SessionTestSuite.java:190)
at junit.framework.TestSuite.run(TestSuite.java:236)
at org.eclipse.core.tests.session.SessionTestSuite.run(SessionTestSuite.java:142)
at org.eclipse.core.tests.session.ConfigurationSessionTestSuite.run(ConfigurationSessionTestSuite.java:235)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at junit.framework.TestSuite.run(TestSuite.java:236)
```

**Comment by merks** [comment]
Are you able to run any specific failing test locally?

**Comment by iloveeclipse** [comment]
> test uses org.eclipse.pde.junit.runtime.coretestapplicationnonmain but doesn't find it

I do see **a lot** of hamcrest related osgi error at test startup **right before** this problem above:

```
!SESSION 2023-08-12 11:11:23.552 -----------------------------------------------
eclipse.buildId=unknown
java.version=17.0.2
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
Framework arguments:  -test org.eclipse.osgi.tests.appadmin.ApplicationAdminTest:testSimpleApp -testpluginname org.eclipse.osgi.tests -version 3 -application org.eclipse.pde.junit.runtime.coretestapplicationnonmain -port 53644
Command-line arguments:  -data C:\tmp\workspace -os win32 -test org.eclipse.osgi.tests.appadmin.ApplicationAdminTest:testSimpleApp -testpluginname org.eclipse.osgi.tests -version 3 -dev file:C:/workspaces/platform/.metadata/.plugins/org.eclipse.pde.core/pde-junit/dev.properties -application org.eclipse.pde.junit.runtime.coretestapplicationnonmain -port 53644 -arch x86_64 -ws win32

!ENTRY org.eclipse.core.tests.harness 4 0 2023-08-12 11:11:24.142
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.core.tests.harness [9]
  Unresolved requirement: Require-Bundle: org.eclipse.jdt.junit4.runtime
    -> Bundle-SymbolicName: org.eclipse.jdt.junit4.runtime; bundle-version="1.3.0.qualifier"; singleton:="true"
       org.eclipse.jdt.junit4.runtime [12]
         Unresolved requirement: Require-Bundle: org.junit; bundle-version="4.7.0"
           -> Bundle-SymbolicName: org.junit; bundle-version="4.13.2.v20230809-1000"
              org.junit [15]
                Unresolved requirement: Require-Bundle: org.hamcrest.core; bundle-version="1.3.0"; visibility:="reexport"
  Unresolved requirement: Require-Bundle: org.eclipse.jdt.junit.runtime
    -> Bundle-SymbolicName: org.eclipse.jdt.junit.runtime; bundle-version="3.7.200.qualifier"; singleton:="true"
       org.eclipse.jdt.junit.runtime [11]
         Unresolved requirement: Require-Bundle: org.junit; bundle-version="3.8.2"
           -> Bundle-SymbolicName: org.junit; bundle-version="4.13.2.v20230809-1000"
  Unresolved requirement: Require-Bundle: org.eclipse.pde.junit.runtime
    -> Bundle-SymbolicName: org.eclipse.pde.junit.runtime; bundle-version="3.7.100.v20230728-0611"; singleton:="true"
       org.eclipse.pde.junit.runtime [13]
         Unresolved requirement: Import-Package: org.eclipse.ui.testing; resolution:="optional"
         Unresolved requirement: Require-Bundle: org.eclipse.jdt.junit.runtime; bundle-version="[3.5.0,4.0.0)"
           -> Bundle-SymbolicName: org.eclipse.jdt.junit.runtime; bundle-version="3.7.200.qualifier"; singleton:="true"
  Unresolved requirement: Require-Bundle: org.eclipse.test.performance
    -> Bundle-SymbolicName: org.eclipse.test.performance; bundle-version="3.19.300.qualifier"; singleton:="true"
       org.eclipse.test.performance [10]
         Unresolved requirement: Require-Bundle: org.junit
           -> Bundle-SymbolicName: org.junit; bundle-version="4.13.2.v20230809-1000"
  Unresolved requirement: Require-Bundle: org.junit
    -> Bundle-SymbolicName: org.junit; bundle-version="4.13.2.v20230809-1000"

	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1852)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1845)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1786)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1750)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1672)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)

!ENTRY org.eclipse.test.performance 4 0 2023-08-12 11:11:24.145
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.test.performance [10]
  Unresolved requirement: Require-Bundle: org.junit
    -> Bundle-SymbolicName: org.junit; bundle-version="4.13.2.v20230809-1000"
       org.junit [15]
         Unresolved requirement: Require-Bundle: org.hamcrest.core; bundle-version="1.3.0"; visibility:="reexport"

	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1852)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1845)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1786)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1750)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1672)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)

!ENTRY org.eclipse.pde.junit.runtime 4 0 2023-08-12 11:11:24.174
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.pde.junit.runtime [13]
  Unresolved requirement: Import-Package: org.eclipse.ui.testing; resolution:="optional"
  Unresolved requirement: Require-Bundle: org.junit; bundle-version="3.8.2"
    -> Bundle-SymbolicName: org.junit; bundle-version="4.13.2.v20230809-1000"
       org.junit [15]
         Unresolved requirement: Require-Bundle: org.hamcrest.core; bundle-version="1.3.0"; visibility:="reexport"
  Unresolved requirement: Require-Bundle: org.eclipse.jdt.junit.runtime; bundle-version="[3.5.0,4.0.0)"
    -> Bundle-SymbolicName: org.eclipse.jdt.junit.runtime; bundle-version="3.7.200.qualifier"; singleton:="true"
       org.eclipse.jdt.junit.runtime [11]
         Unresolved requirement: Require-Bundle: org.junit; bundle-version="3.8.2"
           -> Bundle-SymbolicName: org.junit; bundle-version="4.13.2.v20230809-1000"

	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1852)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1845)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1786)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1750)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1672)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)

!ENTRY org.eclipse.osgi.tests 4 0 2023-08-12 11:11:24.175
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.osgi.tests [20]
  Unresolved requirement: Require-Bundle: org.eclipse.core.tests.harness; bundle-version="3.13.0"
    -> Bundle-SymbolicName: org.eclipse.core.tests.harness; bundle-version="3.15.100.qualifier"; singleton:="true"
       org.eclipse.core.tests.harness [9]
         Unresolved requirement: Require-Bundle: org.eclipse.jdt.junit4.runtime
           -> Bundle-SymbolicName: org.eclipse.jdt.junit4.runtime; bundle-version="1.3.0.qualifier"; singleton:="true"
              org.eclipse.jdt.junit4.runtime [12]
                Unresolved requirement: Require-Bundle: org.junit; bundle-version="4.7.0"
                  -> Bundle-SymbolicName: org.junit; bundle-version="4.13.2.v20230809-1000"
                     org.junit [15]
                       Unresolved requirement: Require-Bundle: org.hamcrest.core; bundle-version="1.3.0"; visibility:="reexport"
         Unresolved requirement: Require-Bundle: org.eclipse.jdt.junit.runtime
           -> Bundle-SymbolicName: org.eclipse.jdt.junit.runtime; bundle-version="3.7.200.qualifier"; singleton:="true"
              org.eclipse.jdt.junit.runtime [11]
                Unresolved requirement: Require-Bundle: org.junit; bundle-version="3.8.2"
                  -> Bundle-SymbolicName: org.junit; bundle-version="4.13.2.v20230809-1000"
         Unresolved requirement: Require-Bundle: org.eclipse.pde.junit.runtime
           -> Bundle-SymbolicName: org.eclipse.pde.junit.runtime; bundle-version="3.7.100.v20230728-0611"; singleton:="true"
              org.eclipse.pde.junit.runtime [13]
                Unresolved requirement: Import-Package: org.eclipse.ui.testing; resolution:="optional"
                Unresolved requirement: Require-Bundle: org.eclipse.jdt.junit.runtime; bundle-version="[3.5.0,4.0.0)"
                  -> Bundle-SymbolicName: org.eclipse.jdt.junit.runtime; bundle-version="3.7.200.qualifier"; singleton:="true"
         Unresolved requirement: Require-Bundle: org.eclipse.test.performance
           -> Bundle-SymbolicName: org.eclipse.test.performance; bundle-version="3.19.300.qualifier"; singleton:="true"
              org.eclipse.test.performance [10]
                Unresolved requirement: Require-Bundle: org.junit
                  -> Bundle-SymbolicName: org.junit; bundle-version="4.13.2.v20230809-1000"
         Unresolved requirement: Require-Bundle: org.junit
           -> Bundle-SymbolicName: org.junit; bundle-version="4.13.2.v20230809-1000"
  Unresolved requirement: Require-Bundle: org.eclipse.test.performance
    -> Bundle-SymbolicName: org.eclipse.test.performance; bundle-version="3.19.300.qualifier"; singleton:="true"

	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1852)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1845)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1786)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1750)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1672)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)

!ENTRY org.junit 2 0 2023-08-12 11:11:24.346
!MESSAGE Could not resolve module: org.junit [15]
  Unresolved requirement: Require-Bundle: org.hamcrest.core; bundle-version="1.3.0"; visibility:="reexport"


!ENTRY org.eclipse.core.tests.harness 2 0 2023-08-12 11:11:24.347
!MESSAGE Could not resolve module: org.eclipse.core.tests.harness [9]
  Unresolved requirement: Require-Bundle: org.eclipse.jdt.junit4.runtime
    -> Bundle-SymbolicName: org.eclipse.jdt.junit4.runtime; bundle-version="1.3.0.qualifier"; singleton:="true"
       org.eclipse.jdt.junit4.runtime [12]
         Unresolved requirement: Require-Bundle: org.junit; bundle-version="4.7.0"
           -> Bundle-SymbolicName: org.junit; bundle-version="4.13.2.v20230809-1000"
              org.junit [15]
                Unresolved requirement: Require-Bundle: org.hamcrest.core; bundle-version="1.3.0"; visibility:="reexport"
  Unresolved requirement: Require-Bundle: org.eclipse.jdt.junit.runtime
    -> Bundle-SymbolicName: org.eclipse.jdt.junit.runtime; bundle-version="3.7.200.qualifier"; singleton:="true"
       org.eclipse.jdt.junit.runtime [11]
         Unresolved requirement: Require-Bundle: org.junit; bundle-version="3.8.2"
           -> Bundle-SymbolicName: org.junit; bundle-version="4.13.2.v20230809-1000"
  Unresolved requirement: Require-Bundle: org.eclipse.pde.junit.runtime
    -> Bundle-SymbolicName: org.eclipse.pde.junit.runtime; bundle-version="3.7.100.v20230728-0611"; singleton:="true"
       org.eclipse.pde.junit.runtime [13]
         Unresolved requirement: Import-Package: org.eclipse.ui.testing; resolution:="optional"
         Unresolved requirement: Require-Bundle: org.eclipse.jdt.junit.runtime; bundle-version="[3.5.0,4.0.0)"
           -> Bundle-SymbolicName: org.eclipse.jdt.junit.runtime; bundle-version="3.7.200.qualifier"; singleton:="true"
  Unresolved requirement: Require-Bundle: org.eclipse.test.performance
    -> Bundle-SymbolicName: org.eclipse.test.performance; bundle-version="3.19.300.qualifier"; singleton:="true"
       org.eclipse.test.performance [10]
         Unresolved requirement: Require-Bundle: org.junit
           -> Bundle-SymbolicName: org.junit; bundle-version="4.13.2.v20230809-1000"
  Unresolved requirement: Require-Bundle: org.junit
    -> Bundle-SymbolicName: org.junit; bundle-version="4.13.2.v20230809-1000"


!ENTRY org.eclipse.osgi.tests 2 0 2023-08-12 11:11:24.348
!MESSAGE Could not resolve module: org.eclipse.osgi.tests [20]
  Unresolved requirement: Require-Bundle: org.eclipse.core.tests.harness; bundle-version="3.13.0"
    -> Bundle-SymbolicName: org.eclipse.core.tests.harness; bundle-version="3.15.100.qualifier"; singleton:="true"
       org.eclipse.core.tests.harness [9]
         Unresolved requirement: Require-Bundle: org.eclipse.jdt.junit4.runtime
           -> Bundle-SymbolicName: org.eclipse.jdt.junit4.runtime; bundle-version="1.3.0.qualifier"; singleton:="true"
              org.eclipse.jdt.junit4.runtime [12]
                Unresolved requirement: Require-Bundle: org.junit; bundle-version="4.7.0"
                  -> Bundle-SymbolicName: org.junit; bundle-version="4.13.2.v20230809-1000"
                     org.junit [15]
                       Unresolved requirement: Require-Bundle: org.hamcrest.core; bundle-version="1.3.0"; visibility:="reexport"
         Unresolved requirement: Require-Bundle: org.eclipse.jdt.junit.runtime
           -> Bundle-SymbolicName: org.eclipse.jdt.junit.runtime; bundle-version="3.7.200.qualifier"; singleton:="true"
              org.eclipse.jdt.junit.runtime [11]
                Unresolved requirement: Require-Bundle: org.junit; bundle-version="3.8.2"
                  -> Bundle-SymbolicName: org.junit; bundle-version="4.13.2.v20230809-1000"
         Unresolved requirement: Require-Bundle: org.eclipse.pde.junit.runtime
           -> Bundle-SymbolicName: org.eclipse.pde.junit.runtime; bundle-version="3.7.100.v20230728-0611"; singleton:="true"
              org.eclipse.pde.junit.runtime [13]
                Unresolved requirement: Import-Package: org.eclipse.ui.testing; resolution:="optional"
                Unresolved requirement: Require-Bundle: org.eclipse.jdt.junit.runtime; bundle-version="[3.5.0,4.0.0)"
                  -> Bundle-SymbolicName: org.eclipse.jdt.junit.runtime; bundle-version="3.7.200.qualifier"; singleton:="true"
         Unresolved requirement: Require-Bundle: org.eclipse.test.performance
           -> Bundle-SymbolicName: org.eclipse.test.performance; bundle-version="3.19.300.qualifier"; singleton:="true"
              org.eclipse.test.performance [10]
                Unresolved requirement: Require-Bundle: org.junit
                  -> Bundle-SymbolicName: org.junit; bundle-version="4.13.2.v20230809-1000"
         Unresolved requirement: Require-Bundle: org.junit
           -> Bundle-SymbolicName: org.junit; bundle-version="4.13.2.v20230809-1000"
  Unresolved requirement: Require-Bundle: org.eclipse.test.performance
    -> Bundle-SymbolicName: org.eclipse.test.performance; bundle-version="3.19.300.qualifier"; singleton:="true"


!ENTRY org.eclipse.test.performance 2 0 2023-08-12 11:11:24.361
!MESSAGE Could not resolve module: org.eclipse.test.performance [10]
  Unresolved requirement: Require-Bundle: org.junit
    -> Bundle-SymbolicName: org.junit; bundle-version="4.13.2.v20230809-1000"
       org.junit [15]
         Unresolved requirement: Require-Bundle: org.hamcrest.core; bundle-version="1.3.0"; visibility:="reexport"


!ENTRY org.eclipse.jdt.junit.runtime 2 0 2023-08-12 11:11:24.363
!MESSAGE Could not resolve module: org.eclipse.jdt.junit.runtime [11]
  Unresolved requirement: Require-Bundle: org.junit; bundle-version="3.8.2"
    -> Bundle-SymbolicName: org.junit; bundle-version="4.13.2.v20230809-1000"
       org.junit [15]
         Unresolved requirement: Require-Bundle: org.hamcrest.core; bundle-version="1.3.0"; visibility:="reexport"


!ENTRY org.eclipse.pde.junit.runtime 2 0 2023-08-12 11:11:24.367
!MESSAGE Could not resolve module: org.eclipse.pde.junit.runtime [13]
  Unresolved requirement: Import-Package: org.eclipse.ui.testing; resolution:="optional"
  Unresolved requirement: Require-Bundle: org.eclipse.jdt.junit.runtime; bundle-version="[3.5.0,4.0.0)"
    -> Bundle-SymbolicName: org.eclipse.jdt.junit.runtime; bundle-version="3.7.200.qualifier"; singleton:="true"
       org.eclipse.jdt.junit.runtime [11]
         Unresolved requirement: Require-Bundle: org.junit; bundle-version="3.8.2"
           -> Bundle-SymbolicName: org.junit; bundle-version="4.13.2.v20230809-1000"
              org.junit [15]
                Unresolved requirement: Require-Bundle: org.hamcrest.core; bundle-version="1.3.0"; visibility:="reexport"


!ENTRY org.eclipse.jdt.junit4.runtime 2 0 2023-08-12 11:11:24.369
!MESSAGE Could not resolve module: org.eclipse.jdt.junit4.runtime [12]
  Unresolved requirement: Require-Bundle: org.junit; bundle-version="4.7.0"
    -> Bundle-SymbolicName: org.junit; bundle-version="4.13.2.v20230809-1000"
       org.junit [15]
         Unresolved requirement: Require-Bundle: org.hamcrest.core; bundle-version="1.3.0"; visibility:="reexport"


!ENTRY org.eclipse.osgi 4 0 2023-08-12 11:11:24.370
!MESSAGE Application error
!STACK 1
java.lang.RuntimeException: Application "org.eclipse.pde.junit.runtime.coretestapplicationnonmain" could not be found in the registry. The applications available are: org.eclipse.equinox.app.error.
	at org.eclipse.equinox.internal.app.EclipseAppContainer.startDefaultApp(EclipseAppContainer.java:252)
	at org.eclipse.equinox.internal.app.MainApplicationLauncher.run(MainApplicationLauncher.java:33)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1459)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1432)
	at org.eclipse.core.launcher.Main.main(Main.java:44)
An error has occurred. See the log file
C:\tmp\8204303379\1691831483661.log.
```

**Comment by merks** [comment]
FYI, I'm suspicious of this and am investigating what this exactly does:

https://github.com/eclipse-platform/eclipse.platform/blob/5fdd3cc9d9ca187fc6540b66ac661ae1e37089eb/runtime/tests/org.eclipse.core.tests.harness/src/org/eclipse/core/tests/session/ConfigurationSessionTestSuite.java#L95

**Comment by merks** [comment]
Yes, I see the org.hamcrest 2.x bundle is added:

![image](https://github.com/eclipse-equinox/equinox/assets/208716/019f1ffe-476a-4289-971f-e1615db9dae0)

But of course not the org.hamcrest.core 2.x bundle because it's just a placeholder, but OSGi resolution of org.junit requires some version of org.hamcrest.core which is being minimized away but this logic.

I'll need to find a workaround...

**Comment by laeubi** [comment]
It seems you can add bundles by their ID:

https://github.com/eclipse-platform/eclipse.platform/blob/5fdd3cc9d9ca187fc6540b66ac661ae1e37089eb/runtime/tests/org.eclipse.core.tests.harness/src/org/eclipse/core/tests/session/ConfigurationSessionTestSuite.java#L103

so maybe 

```
addBundle(org.hamcrest.CoreMatchers.class); // real code
addBundle("org.hamcrest.core"); // placeholder
```

**Comment by HannesWell** [comment]
> so maybe
> 
> ```
> addBundle(org.hamcrest.CoreMatchers.class); // real code
> addBundle("org.hamcrest.core"); // placeholder
> ```

Sounds good.
In general I think it would be better to compute the required dependencies automatically based on the wiring.

**Comment by merks** [comment]
I know that the implementation here not pretty, but the goal is to get the tests working, not to fix the questionable fragile design...

**Comment by iloveeclipse** [comment]
Fixed via https://github.com/eclipse-platform/eclipse.platform/pull/637
