### ISSUE TITLE
Could not resolve module: org.apache.aries.spifly.dynamic.bundle

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-equinox/equinox#302]
I see this error with 4.29.0.I20230811-1800 SDK build on first startup, or on every startup with "-clean" argument.

```
eclipse.buildId=4.29.0.I20230811-1800
java.version=17.0.2
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -clean

org.apache.aries.spifly.dynamic.bundle
Error
Sat Aug 12 10:51:41 CEST 2023
FrameworkEvent ERROR

org.osgi.framework.BundleException: Could not resolve module: org.apache.aries.spifly.dynamic.bundle [2]
  Unresolved requirement: Import-Package: org.objectweb.asm; version="[9.4.0,10.0.0)"

	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1852)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1845)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1788)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1750)
	at org.eclipse.osgi.container.SystemModule.startWorker(SystemModule.java:269)
	at org.eclipse.osgi.container.Module.doStart(Module.java:605)
	at org.eclipse.osgi.container.Module.start(Module.java:468)
	at org.eclipse.osgi.container.SystemModule.start(SystemModule.java:193)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:445)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:464)
	at org.eclipse.osgi.launch.Equinox.start(Equinox.java:139)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.startup(EclipseStarter.java:338)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:251)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1459)
```

**Comment by merks** [comment]
I was about to report this too.  

All these asm bundles are installed so the package must actually be available:

![image](https://github.com/eclipse-equinox/equinox/assets/208716/af7ed427-e561-4a5b-aeab-f87e2976c3b4)

This is probably related to some early start behavior that @HannesWell has been working on to support hooking up a logging framework...

**Comment by laeubi** [comment]
> All these asm bundles are installed so the package must actually be available:

An installed bundle is not necessarily a resolved bundle see: https://docs.osgi.org/specification/osgi.core/7.0.0/framework.lifecycle.html#d0e9143

**Comment by merks** [comment]
That's all true.  

I'm familiar with those bundles though.  They export packages like this:

![image](https://github.com/eclipse-equinox/equinox/assets/208716/0da42f10-5de4-4588-801c-4f6a566ad085)

I also know that @HannesWell has been working on early start stuff and aeries :

https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/commit/b9cb4799d5d0e49129e93c2c3523731a1bba1d94

So I can only theorize why the package doesn't resolved, or the bundle it contains doesn't resolve, but it's the above changes that are new and related in this regard...

**Comment by HannesWell** [comment]
> Also note that the **bundle-version** do not tell anything about exported **package-version**.

That's right, but I assume asm exports them in the same version.

> 
> And finally the start order has nothing to do with the resolution of a package import.

Right.

I can have a look in a few minutes, just have to finish another task.

**Comment by laeubi** [comment]
> I also know that @HannesWell has been working on early start stuff and aeries :

But early startup does not change the result of the resolve ... so first thing would be to open the OSGi Host Console and see if it is only an intermediate or permanent resolve error.

**Comment by merks** [comment]
@laeubi 

You clearly know much more about this.   The console says this so I assume in the end it does resolve:
```
org.objectweb.asm_9.5.0 [324]
  Id=324, Status=RESOLVED    Data Root=D:\Users\test17\sdk-latest\eclipse\configuration\org.eclipse.osgi\324\data  "No registered services."
```

**Comment by laeubi** [comment]
To be sure you can take a look at `org.apache.aries.spifly.dynamic.bundle` as well, I think this could be related to a recent change in equinox where it not (implicitly) resolves *ALL* bundles, so there could be a state where some bundles are still in `INSTALLED` state, then simple-configurator kicks in and triggers the resolve/refresh (e.g. asm bundles might only be installed by simpleconfigurator!) and then afterwards everything is fine.

So I think either *all* dependencies of spyfly must be on startlevel 1 (so they are ignored by simpleconfigurator), or their startlevel should be raise above that of simpleconfigurator.

**Comment by HannesWell** [comment]
@merks in my Platform workspace the Releng Aggregator targlet fails to resolve the org.junit and hamcrest from the eclipse-sdk-prereqs.target:

![grafik](https://github.com/eclipse-equinox/equinox/assets/44067969/6c0e91e6-9970-43e7-92e1-0deb2f0512a8)

If I run the setup the Modular Target task also fails correspondingly:
```
ERROR: org.eclipse.oomph.targlets.core code=0 Resolution problems
  at org.eclipse.oomph.targlets.internal.core.TargletContainer.forceUpdate(TargletContainer.java:919)
  at org.eclipse.oomph.setup.targlets.impl.TargletTaskImpl$4.run(TargletTaskImpl.java:1232)
  at org.eclipse.oomph.util.pde.TargetPlatformUtil.runWithTargetPlatformService(TargetPlatformUtil.java:120)
  at org.eclipse.oomph.setup.targlets.impl.TargletTaskImpl.perform(TargletTaskImpl.java:1092)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3864)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil$1.run(SetupTaskPerformer.java:5200)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2453)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2478)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.performNeededSetupTasks(SetupTaskPerformer.java:5193)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:3798)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:3773)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:3651)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:592)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:721)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
  ERROR: org.eclipse.oomph.targlets.core code=0 Problems resolving composed target 'eclipse-sdk-prereqs'
    ERROR: org.eclipse.pde.core code=0 Problems occurred while resolving the target contents
      ERROR: org.eclipse.pde.core code=0 Problems loading repositories
        ERROR: org.eclipse.pde.core code=0 Unable to locate installable unit org.junit 4.13.2.v20230809-1000
        ERROR: org.eclipse.pde.core code=0 Unable to locate installable unit org.junit.source 4.13.2.v20230809-1000
        ERROR: org.eclipse.pde.core code=0 Unable to locate installable unit org.hamcrest.core 1.3.0.v20230809-1000
        ERROR: org.eclipse.pde.core code=0 Unable to locate installable unit org.hamcrest.core.source 1.3.0.v20230809-1000
        ERROR: org.eclipse.pde.core code=0 Unable to locate installable unit org.hamcrest.core 2.2.0.v20230809-1000
        ERROR: org.eclipse.pde.core code=0 Unable to locate installable unit org.hamcrest.core.source 2.2.0.v20230809-1000
```

However if I resolve the target directly it works perfectly fine. I also verified the https://download.eclipse.org/tools/orbit/simrel/maven-bnd/nightly/latest p2-repo directly and of course the bundles are present in that version.
Could it be that  the Oomph targlet does not update the cached content of the nightly-repo correctly?

**Comment by merks** [comment]
One never knows with PDE and p2 what's cached and what is not refreshed.  Sometimes restarting helps.  In the worst case I use Window -> Preferences -> Oomph -> Bundle Pools -> Clean Cache so that all p2 sites must be loaded from the server.

**Comment by HannesWell** [comment]
> One never knows with PDE and p2 what's cached and what is not refreshed. Sometimes restarting helps. In the worst case I use Window -> Preferences -> Oomph -> Bundle Pools -> Clean Cache so that all p2 sites must be loaded from the server.

Yes that plus deleting the PDE bundle pool and the .p2 folder in my workspace configuration worked (I tried all together).
But I won't have time to look into this this evening. Will do it tomorrow.

**Comment by HannesWell** [comment]
> I see this error with 4.29.0.I20230811-1800 SDK build on first startup, or on every startup with "-clean" argument.

I can reproduce this with a fresh SDK, but not when using the `eclipsec.exe -clean` option.

Interestingly I cannot reproduce it with an Eclipse launched from the IDE.

> So I think either _all_ dependencies of spyfly must be on startlevel 1 (so they are ignored by simpleconfigurator), or their startlevel should be raise above that of simpleconfigurator.

Indeed this is fixed in a fresh SDK when I set the spi-fly with level 2.
Since I think it is bad to manually handle all dependencies I think we should lift spi-fly to level 2.
I'll check this evening if anything needs spi-fly in level 1 or 2 and moving it to two could cause harm.

**Comment by HannesWell** [comment]
> I'll check this evening if anything needs spi-fly in level 1 or 2 and moving it to two could cause harm.

I looked into this and surprisingly there are really a lot of bundles activated in level 2, so I'm not so confident to move it.

> To be sure you can take a look at `org.apache.aries.spifly.dynamic.bundle` as well, I think this could be related to a recent change in equinox where it not (implicitly) resolves _ALL_ bundles, so there could be a state where some bundles are still in `INSTALLED` state, then simple-configurator kicks in and triggers the resolve/refresh (e.g. asm bundles might only be installed by simpleconfigurator!) and then afterwards everything is fine.

I debugged this a bit and it looks like that initially (in `ModuleContainer.incStartLevel` with `toStartLevel=1`) only o.e.osgi and the simple-configurator are installed. When the simple-configurator is activated it applies the configuration and installs all other bundles. ~~In ConfigApplier.install(URL,boolean) it then also activates all bundles that are marked as auto-start, regardless of their specified start-level and in what level the framework is currently, which seem not to be correct.
Intuitively I would say, that only those bundles that have a start-level equal or lower the framework's current level.~~
Edit: ConfigApplierInstall calls start() for all Bundles that are auto-started at any level, but the framework does not perform the activation if the start-level is not yet met.
But immediatly before it resolves all installed bundles, so I do not really understand why this happens.
Furthermore I now cannot reproduce this bug's behaviour anymore even with a freshly unzipped sdk...

**Comment by laeubi** [comment]
> Furthermore I now cannot reproduce this bug's behaviour anymore even with a freshly unzipped sdk...

Make sure to use the `-clean` flag otherwise the resolved state will be cached.

> I debugged this a bit and it looks like that initially (in ModuleContainer.incStartLevel with toStartLevel=1) only o.e.osgi and the simple-configurator are installed.

Actually all bundles with start-level = 1 should be started (but you can look at `config.ini` to be sure)

**Comment by tjwatson** [comment]
The only way I can see this happening is if the `osgi.bundles` setting in the `config.ini` had the `org.apache.aries.spifly.dynamic.bundle` in the list along with simpleconfigurator and somehow it got installed first and started before simpleconfigurator.  Otherwise simpleconfigurator should have installed all the other bundles before trying to start spifly.

**Comment by HannesWell** [comment]
> The only way I can see this happening is if the `osgi.bundles` setting in the `config.ini` had the `org.apache.aries.spifly.dynamic.bundle` in the list along with simpleconfigurator and somehow it got installed first and started before simpleconfigurator.

Yes that's indeed the case, an excerpt from the config.ini:
```
osgi.bundles=reference\:file\:org.apache.aries.spifly.dynamic.bundle_1.3.6.jar@1\:start,reference\:file\:org.eclipse.equinox.simpleconfigurator_1.4.300.v20230630-1506.jar@1\:start
eclipse.p2.data.area=@config.dir/../p2
eclipse.p2.profile=SDKProfile
osgi.framework=file\:plugins/org.eclipse.osgi_3.18.500.v20230801-1826.jar
osgi.framework.extensions=reference\:file\:org.eclipse.osgi.compatibility.state_1.2.800.v20221116-1440.jar
```
And when I put a break-point into `ModuleContainer.incStartLevel()` I see that the aries.spifly.bundle is activated before the simpleconfigurator.

https://github.com/eclipse-equinox/equinox/blob/cfed903b766475c1710d7ae208853f0ba5f1d9cd/bundles/org.eclipse.osgi/container/src/org/eclipse/osgi/container/ModuleContainer.java#L1848-L1854

In the callers aries is listed as the bundle activated first after the framework:

![grafik](https://github.com/eclipse-equinox/equinox/assets/44067969/5a1baa2a-231e-42c3-a30a-ae92851390b2)

And if the framework attempts to activate aries I also can see the exception catched in line 1854 of the ModuleContainer:
```
org.osgi.framework.BundleException: Could not resolve module: org.apache.aries.spifly.dynamic.bundle [2]
  Unresolved requirement: Import-Package: org.objectweb.asm; version="[9.4.0,10.0.0)"
```
But this error is not logged to the console anymore (IIRC it was printed in an earlier testing), however if the workspace is fully started I see the error in the Error log view, so I can reproduce the error.

Nevertheless I see the print-out from Aries that the slf4j.simple provider was registered:
```
INFORMATION: Registered provider org.slf4j.simple.SimpleServiceProvider of service org.slf4j.spi.SLF4JServiceProvider in bundle slf4j.simple
```
So it looks like everything still works. My theory is that although the first attempt to start aries initially by the framework fails simpleconfigurator tries it again after it has installed all other bundles and then succeeds to activate aries.
So this seems to be only an alarming print-out that does not really cause any trouble.

@merks, @iloveeclipse do you see the aries print-out from above as well?

If I swap the simpleconfigurator to be the first element in the `osgi.bundles` entry in the config.ini:
`osgi.bundles=reference\:file\:org.eclipse.equinox.simpleconfigurator_1.4.300.v20230630-1506.jar@1\:start,reference\:file\:org.apache.aries.spifly.dynamic.bundle_1.3.6.jar@1\:start`
Then everything works without any error.

Lets see if https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1252 is already sufficient. If yes, we should stop to sort the configuration entries alphabetically in PDE.

**Comment by tjwatson** [comment]
This may be too drastic of a change to rush into:

Perhaps simple configurator should be a system.bundle fragment with an `ExtensionBundle-Activator`

```
Fragment-Host: system.bundle
ExtensionBundle-Activator: org.eclipse.equinox.internal.simpleconfigurator.Activator
```

I'm sure that will disrupt all sorts of things unforseen.  But it would ensure the simple configurator is run before even reaching start-level 1 during startup.

But in this particular case I question why spifly has to be on `osgi.bundles` setting at all instead of be installed by simple configurator with its `bundles.info`.
