### ISSUE TITLE
SecurityException in XMLParsingServiceFactory.getService() / lsp4e

### ISSUE THREAD

**Issue by jukzi** [eclipse-equinox/equinox#303]
```
org.osgi.framework.ServiceException: Exception in org.eclipse.osgi.internal.framework.XMLParsingServiceFactory.getService()
	at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.factoryGetService(ServiceFactoryUse.java:228)
	at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.getService(ServiceFactoryUse.java:114)
	at org.eclipse.osgi.internal.serviceregistry.ServiceConsumer$2.getService(ServiceConsumer.java:48)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.getService(ServiceRegistrationImpl.java:568)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.getService(ServiceRegistry.java:542)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.getService(BundleContextImpl.java:660)
	at org.eclipse.core.runtime.ServiceCaller.lambda$7(ServiceCaller.java:388)
	at java.base/java.util.Optional.map(Optional.java:260)
	at org.eclipse.core.runtime.ServiceCaller.getCurrent(ServiceCaller.java:387)
	at org.eclipse.core.runtime.ServiceCaller.callOnce(ServiceCaller.java:158)
	at org.eclipse.core.runtime.ServiceCaller.callOnce(ServiceCaller.java:140)
	at org.eclipse.core.internal.content.XMLRootHandler.parseContents(XMLRootHandler.java:158)
	at org.eclipse.core.runtime.content.XMLRootElementContentDescriber2.fillContentProperties(XMLRootElementContentDescriber2.java:206)
	at org.eclipse.core.runtime.content.XMLRootElementContentDescriber2.checkCriteria(XMLRootElementContentDescriber2.java:135)
	at org.eclipse.core.runtime.content.XMLRootElementContentDescriber2.describe(XMLRootElementContentDescriber2.java:174)
	at org.eclipse.core.internal.content.ContentTypeCatalog.describe(ContentTypeCatalog.java:271)
	at org.eclipse.core.internal.content.ContentTypeCatalog.collectMatchingByContents(ContentTypeCatalog.java:246)
	at org.eclipse.core.internal.content.ContentTypeCatalog.internalFindContentTypesFor(ContentTypeCatalog.java:470)
	at org.eclipse.core.internal.content.ContentTypeCatalog.internalFindContentTypesFor(ContentTypeCatalog.java:529)
	at org.eclipse.core.internal.content.ContentTypeCatalog.findContentTypesFor(ContentTypeCatalog.java:363)
	at org.eclipse.core.internal.content.ContentTypeMatcher.findContentTypesFor(ContentTypeMatcher.java:57)
	at org.eclipse.lsp4e.LSPEclipseUtils.getDocumentContentTypes(LSPEclipseUtils.java:1284)
	at org.eclipse.lsp4e.LanguageServiceAccessor.getLSWrappers(LanguageServiceAccessor.java:291)
	at org.eclipse.lsp4e.LanguageServers$LanguageServerDocumentExecutor.getServers(LanguageServers.java:272)
	at org.eclipse.lsp4e.LanguageServers.executeOnServers(LanguageServers.java:403)
	at org.eclipse.lsp4e.LanguageServers.collectAll(LanguageServers.java:76)
	at org.eclipse.lsp4e.LanguageServers.collectAll(LanguageServers.java:58)
	at org.eclipse.lsp4e.ConnectDocumentToLanguageServerSetupParticipant.lambda$0(ConnectDocumentToLanguageServerSetupParticipant.java:60)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.SecurityException: setContextClassLoader
	at java.base/java.util.concurrent.ForkJoinWorkerThread$InnocuousForkJoinWorkerThread.setContextClassLoader(ForkJoinWorkerThread.java:210)
	at org.eclipse.osgi.internal.framework.XMLParsingServiceFactory.getService(XMLParsingServiceFactory.java:53)
	at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse$1.run(ServiceFactoryUse.java:218)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.factoryGetService(ServiceFactoryUse.java:215)
	... 34 more

```
```

eclipse.buildId=4.29.0.I20230814-1800
java.version=17.0.8
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
Command-line arguments:  -os win32 -ws win32 -arch x86_64

```

What i did: search for "1" in *.xml and press "Show next match" multiple times - was not reproducible that way though
![image](https://github.com/eclipse-equinox/equinox/assets/51790620/ec8dd0bd-7e6c-44fc-90e4-ca48a9be44ab)

I have seen similar exception in a previous report:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=569286#c24

**Comment by tjwatson** [comment]
Try setting `eclipse.parsers.setTCCL=false` in the `config.ini`

Perhaps it is time to flip the default of this to `false`:

https://github.com/eclipse-equinox/equinox/blob/cfed903b766475c1710d7ae208853f0ba5f1d9cd/bundles/org.eclipse.osgi/container/src/org/eclipse/osgi/internal/framework/SystemBundleActivator.java#L119

At least we should catch such exceptions like this when running on the fork/join thread pool and continue on without doing the TCCL switch.

**Comment by tjwatson** [comment]
https://github.com/eclipse-equinox/equinox/blob/cfed903b766475c1710d7ae208853f0ba5f1d9cd/bundles/org.eclipse.osgi/container/src/org/eclipse/osgi/internal/framework/XMLParsingServiceFactory.java#L38-L58

Is the place with the comment on why we were doing this for https://bugs.eclipse.org/bugs/show_bug.cgi?id=285505

**Comment by tjwatson** [comment]
My ironic comment in https://bugs.eclipse.org/bugs/show_bug.cgi?id=285505#c9 is coming to fruition.

**Comment by guw** [comment]
@tjwatson I am seeing another instance of this (again with LSP4E). It broke after updating the installation to 2023-12. Before it was running without this exception. 

According to [this discussion](https://concurrency-interest.altair.cs.oswego.narkive.com/X078lHiy/side-effect-of-the-new-forkjoinpool-commonpool-innocuousforkjoinworkerthreadfactory) a SecurityManager might be responsible. I do know the Ant editor installs one and I think the Takari Maven extension/plug-in installs one too.

But this worked in 2023-09. Plug-ins have only been updated. Maybe this changed activation.

```
java.util.concurrent.CompletionException: java.lang.RuntimeException: Exception occurred while creating an instance of the stream connection provider
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.RuntimeException: Exception occurred while creating an instance of the stream connection provider
	at org.eclipse.lsp4e.LanguageServersRegistry$ExtensionLanguageServerDefinition.createConnectionProvider(LanguageServersRegistry.java:172)
	at org.eclipse.lsp4e.LanguageServerWrapper.lambda$0(LanguageServerWrapper.java:288)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	... 6 more
Caused by: org.eclipse.core.runtime.CoreException: Plug-in org.eclipse.wildwebdeveloper.xml was unable to load class org.eclipse.wildwebdeveloper.xml.internal.XMLLanguageServer.
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.throwException(RegistryStrategyOSGI.java:242)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:225)
	at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:987)
	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:255)
	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:65)
	at org.eclipse.lsp4e.LanguageServersRegistry$ExtensionLanguageServerDefinition.createConnectionProvider(LanguageServersRegistry.java:169)
	... 8 more
Caused by: java.lang.ClassNotFoundException: An error occurred while automatically activating bundle org.eclipse.wildwebdeveloper.xml (1537).
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:126)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:570)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:335)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:397)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:500)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:416)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:168)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.loadClass(EquinoxBundle.java:622)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:223)
	... 12 more
Caused by: org.osgi.framework.BundleException: Exception in org.eclipse.wildwebdeveloper.xml.internal.Activator.start() of bundle org.eclipse.wildwebdeveloper.xml.
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:839)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:767)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1032)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:371)
	at org.eclipse.osgi.container.Module.doStart(Module.java:605)
	at org.eclipse.osgi.container.Module.start(Module.java:468)
	at org.eclipse.osgi.framework.util.SecureAction$22.run(SecureAction.java:520)
	at org.eclipse.osgi.framework.util.SecureAction$22.run(SecureAction.java:1)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:517)
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:117)
	... 21 more
Caused by: java.lang.SecurityException: setContextClassLoader
	at java.base/java.util.concurrent.ForkJoinWorkerThread$InnocuousForkJoinWorkerThread.setContextClassLoader(ForkJoinWorkerThread.java:210)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.setContextFinder(BundleContextImpl.java:850)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:815)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:1)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:810)
	... 31 more
```

**Comment by tjwatson** [comment]
Without knowing what Security Manager is doing this

> According to [this discussion](https://concurrency-interest.altair.cs.oswego.narkive.com/X078lHiy/side-effect-of-the-new-forkjoinpool-commonpool-innocuousforkjoinworkerthreadfactory) a SecurityManager might be responsible. I do know the Ant editor installs one and I think the Takari Maven extension/plug-in installs one too.

No, this is not a security manager.  See java.base/java.util.concurrent.ForkJoinWorkerThread$InnocuousForkJoinWorkerThread.setContextClassLoader(ForkJoinWorkerThread.java:210) implementation:

```java
        @Override // paranoically
        public void setContextClassLoader(ClassLoader cl) {
            throw new SecurityException("setContextClassLoader");
        }
```

It just always will fail.  If you would like to contribute a PR, I suggest we catch the security exception here and move on without setting the TCCL.
