### ISSUE TITLE
org.eclipse.equinox.console cannot go beyond start level 6 

### ISSUE THREAD

**Issue by laeubi** [eclipse-equinox/equinox#48]
If I try to start my eclipse application with a higher default level (equinox default 4) everything works fine unless I try to set a higher value than 6 where I get:

```
!ENTRY org.eclipse.osgi 4 0 2022-06-20 09:04:44.104
!MESSAGE Could not start bundle: org.eclipse.equinox.console
!STACK 0
org.osgi.framework.BundleException: Could not start bundle: org.eclipse.equinox.console
	at org.eclipse.core.runtime.internal.adaptor.ConsoleManager.checkForConsoleBundle(ConsoleManager.java:75)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.startup(EclipseStarter.java:352)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:251)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
Caused by: org.osgi.framework.BundleException: Cannot transiently start a module whose start level is not met. osgi.identity; type="osgi.bundle"; version:Version="1.4.500.v20211021-1418"; osgi.identity="org.eclipse.equinox.console" [id=427]
	at org.eclipse.osgi.container.Module.start(Module.java:431)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:445)
	at org.eclipse.core.runtime.internal.adaptor.ConsoleManager.checkForConsoleBundle(ConsoleManager.java:73)
	... 10 more
Root exception:
org.osgi.framework.BundleException: Cannot transiently start a module whose start level is not met. osgi.identity; type="osgi.bundle"; version:Version="1.4.500.v20211021-1418"; osgi.identity="org.eclipse.equinox.console" [id=427]
	at org.eclipse.osgi.container.Module.start(Module.java:431)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:445)
	at org.eclipse.core.runtime.internal.adaptor.ConsoleManager.checkForConsoleBundle(ConsoleManager.java:73)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.startup(EclipseStarter.java:352)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:251)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
```

What I do is:

1. Start the product --> everything is fine
2. Go to the launch config / Plugins Tab and raise default level to 5 --> works
3. Go to the launch config / Plugins Tab and raise default level to 6 --> works
4. Go to the launch config / Plugins Tab and raise default level to 7 --> fails

**Comment by tjwatson** [comment]
This is because the equinox specific property `osgi.bundles.defaultStartLevel` defaults to 4 which controls the default start-level of bundles while the equinox specific property `osgi.startLevel` controls the framework start-level that the `EclipseStarter` class uses defaults to 6.  I can think of no good reason the `osgi.startLevel` has a default as low as 6.  I suggest we significantly raise that to something like `100` or more.

This impacts all bundles if `osgi.bundles.defaultStartLevel` is < `osgi.startLevel` and will prevent all bundles from being activated unless they have their start-level set explicitly by p2 I think.  At the very least we should ensure the default for `osgi.bundles.defaultStartLevel` is set to something < what is being used for `osgi.startLevel`.

**Comment by laeubi** [comment]
Ah thanks, I didn't know there are two "defaults", I already opened a discussion here:
- https://github.com/eclipse-equinox/equinox/discussions/49

and wondering why there are two distinct levels at all?

**Comment by laeubi** [comment]
Still an issue
