### ISSUE TITLE
Exception saving preferences in p2 tasks

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-equinox/equinox#7]
While executing p2 tasks from command line we see on 4.24 M3 following errors reported:
```
!ENTRY org.eclipse.equinox.preferences 4 4 2022-06-01 08:42:59.310
!MESSAGE Exception saving preferences to: /workspaces/socbm775/sandreev/ws-r7.6-ewc425/opt/93000/src/segments/eclipse/eclipseRE/p2/org.eclipse.equinox.p2.engine/profileRegistry/SDKProfile.profile/.data/.settings/org.eclipse.equinox.p2.artifact.repository.prefs.
!STACK 0
java.nio.file.NoSuchFileException: /workspaces/socbm775/sandreev/ws-r7.6-ewc425/opt/93000/src/segments/eclipse/eclipseRE/p2/org.eclipse.equinox.p2.engine/profileRegistry/SDKProfile.profile/.data/.settings/org.eclipse.equinox.p2.artifact.repository.prefs
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:468)
        at java.base/sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:267)
        at java.base/java.nio.file.Files.move(Files.java:1422)
        at org.eclipse.core.internal.preferences.EclipsePreferences.write(EclipsePreferences.java:289)
        at org.eclipse.core.internal.preferences.EclipsePreferences.save(EclipsePreferences.java:1066)
        at org.eclipse.equinox.internal.p2.engine.ProfilePreferences.doSave(ProfilePreferences.java:141)
        at org.eclipse.equinox.internal.p2.engine.ProfilePreferences$SaveJob.run(ProfilePreferences.java:54)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

Most likely regression from https://github.com/eclipse-equinox/equinox.bundles/pull/8

**Comment by tjwatson** [comment]
@HannesWell can you provide a PR to address this issue?

**Comment by iloveeclipse** [comment]
The problem is still there. 
```
!ENTRY org.eclipse.equinox.p2.engine 2 0 2022-07-05 07:44:30.041
!MESSAGE Exception saving profile preferences
!STACK 0
org.osgi.service.prefs.BackingStoreException: Exception saving preferences to: /truncated/eclipseRE/p2/org.eclipse.equinox.p2.engine/profileRegistry/SDKProfile.profile/.data/.settings/org.eclipse.equinox.p2.metadata.repository.prefs.
        at org.eclipse.core.internal.preferences.EclipsePreferences.write(EclipsePreferences.java:300)
        at org.eclipse.core.internal.preferences.EclipsePreferences.save(EclipsePreferences.java:1070)
        at org.eclipse.equinox.internal.p2.engine.ProfilePreferences.doSave(ProfilePreferences.java:141)
        at org.eclipse.equinox.internal.p2.engine.ProfilePreferences$SaveJob.run(ProfilePreferences.java:54)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.nio.file.NoSuchFileException: /truncated/eclipseRE/p2/org.eclipse.equinox.p2.engine/profileRegistry/SDKProfile.profile/.data/.settings/org.eclipse.equinox.p2.metadata.repository.prefs
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:468)
        at java.base/sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:267)
        at java.base/java.nio.file.Files.move(Files.java:1422)
        at org.eclipse.core.internal.preferences.EclipsePreferences.write(EclipsePreferences.java:292)
        ... 4 more
```
