### ISSUE TITLE
org.eclipse.core.internal.net.Activator fails to start with missing passwordprovider

### ISSUE THREAD

**Issue by laeubi** [eclipse-equinox/equinox#99]
```
org.eclipse.equinox.security.storage.StorageException: Unable to locate secure storage module (org.eclipse.tycho.noopsecurity.id1).
	at org.eclipse.equinox.internal.security.storage.PasswordProviderSelector.findStorageModule(PasswordProviderSelector.java:211)
	at org.eclipse.equinox.internal.security.storage.SecurePreferencesRoot.getModulePassword(SecurePreferencesRoot.java:237)
	at org.eclipse.equinox.internal.security.storage.SecurePreferencesRoot.getPassword(SecurePreferencesRoot.java:230)
	at org.eclipse.equinox.internal.security.storage.SecurePreferences.get(SecurePreferences.java:267)
	at org.eclipse.equinox.internal.security.storage.SecurePreferencesWrapper.get(SecurePreferencesWrapper.java:123)
	at org.eclipse.core.internal.net.ProxyType.loadProxyAuth(ProxyType.java:559)
	at org.eclipse.core.internal.net.ProxyType.createProxyData(ProxyType.java:145)
	at org.eclipse.core.internal.net.ProxyType.getProxyData(ProxyType.java:134)
	at org.eclipse.core.internal.net.ProxyType.initialize(ProxyType.java:539)
	at org.eclipse.core.internal.net.ProxyManager.initialize(ProxyManager.java:262)
	at org.eclipse.core.internal.net.Activator.start(Activator.java:177)
```

Instead it should simply handle this as if there is no password available!

**Comment by laeubi** [comment]
Actually this is only printed as an error, but the code just goes on, this is very bad as it leaves the user with the feeling something goes wrong....
